/** What each Chinese kitchen cooks: the hero first, then the dishes the place is known for. Owned by the Researcher. */
// Keyed by the world object's id (see graph.ts); a room is looked up through the object that opens it,
// so `noodle` carries the noodle shop's list, `wok` the home kitchen's and `aromatics` the village market's.
// A `recipe` is the id of a recipe in public/static/recipes.json that is that exact dish; the recipe add-on
// reads this list, it never writes it.
export type RepertoireEntry = { name: string; zh?: string; line: string; recipe?: string };

export const CHINA_REPERTOIRE: Record<string, RepertoireEntry[]> = {
  // ---------- Sichuan ----------
  hotpot: [
    { name: "Málà hotpot", zh: "麻辣火锅", line: "The house pot: beef tallow, chilli and Sichuan pepper boiled down into the broth everything else is cooked in." },
    { name: "Divided pot", zh: "鸳鸯锅", line: "A ring of clear broth around the red one, ordered when the table has a child or a guest from another province." },
    { name: "Ox tripe", zh: "毛肚", line: "The plate the pot is judged by: held in the red side for seven or eight seconds, no longer, and eaten crisp." },
    { name: "Duck intestine", zh: "鸭肠", line: "Swished strand by strand in the boiling centre until it curls, the second thing a Chongqing table orders." },
    { name: "Duck blood", zh: "鸭血", line: "Soft slabs left in the pot to take up chilli oil while the meat plates come and go." },
    { name: "Crisp-fried pork", zh: "酥肉", line: "Pork strips fried in batter, eaten dry from the plate or dropped back into the broth to soften." },
    { name: "Ice jelly", zh: "冰粉", line: "A cold bowl of set jelly under brown sugar syrup, eaten after the pot to put the chilli out." },
  ],
  noodle: [
    { name: "Dan dan noodles", zh: "担担面", line: "Chilli oil, sesame paste, vinegar and crumbled fried pork at the bottom of the bowl, noodles on top, mixed by you.", recipe: "3e98be51-a57e-4147-ac3d-2f3f3b047a90" },
    { name: "Sweet-water noodles", zh: "甜水面", line: "Noodles as thick as a pencil under sweetened soy and chilli oil, chewy enough to be sold by the small bowl." },
    { name: "Hot-and-sour noodles", zh: "酸辣粉", line: "Glassy sweet-potato starch noodles in a hot-and-sour broth with peanuts, preserved vegetable and a great deal of vinegar." },
    { name: "Red-oil wontons", zh: "红油抄手", line: "Thin-skinned pork wontons boiled and laid in chilli oil with sweetened soy and garlic, never in soup." },
    { name: "Zhong dumplings in red oil", zh: "钟水饺", line: "Pork dumplings under red oil and sweetened soy, sold at Zhong's stall from the 1890s and copied by every shop since.", recipe: "3d695c6d-26b4-8198-9e41-e3e8df8bb4fa" },
    { name: "Yibin burning noodles", zh: "宜宾燃面", line: "Dry noodles from Yibin, heavily oiled and tossed with crushed peanuts and preserved vegetable, with no broth at all." },
    { name: "Beef noodles", zh: "牛肉面", line: "Red-braised beef ladled over noodles, the braise Sichuan soldiers carried to Taiwan in 1949 and left there." },
    { name: "Pea and pork noodles", zh: "豌杂面", line: "Stewed yellow peas and minced pork on one bowl of noodles, the cheapest full lunch the shop sells." },
  ],
  teahouse: [
    { name: "Jasmine tea in a lid-cup", zh: "盖碗茉莉花茶", line: "The house cup: jasmine leaves in a gaiwan, refilled from a long-spouted kettle for as long as you sit." },
    { name: "Mengding green tea", zh: "蒙顶甘露", line: "A green tea from the hills west of Chengdu, drunk plain in a glass so the leaves can be watched." },
    { name: "Egg pancakes", zh: "蛋烘糕", line: "Small batter cakes cooked in a copper mould over charcoal and folded around sweet or salty fillings." },
    { name: "Three cannon shots", zh: "三大炮", line: "Glutinous rice balls thrown at a brass tray so they bang, then rolled in soy flour and sugar syrup." },
    { name: "Sugar-oil dumplings", zh: "糖油果子", line: "Glutinous balls fried in caramel until they are dark and sticky, sold three to a skewer at the garden gate." },
    { name: "Melon seeds and peanuts", zh: "瓜子花生", line: "What stays on the table between refills, cracked one at a time while the mahjong goes on." },
  ],
  aromatics: [
    { name: "Brined deli plate", zh: "卤菜", line: "Duck wings, beef shin and tofu skin simmered in a spiced brine kept going for years, chopped cold to order." },
    { name: "Fuqi feipian", zh: "夫妻肺片", line: "Sliced beef and offal under chilli oil, ground Sichuan pepper and celery, the cold counter's most-copied dish since the 1930s." },
    { name: "Mouthwatering chicken", zh: "口水鸡", line: "Poached chicken chopped and drowned in red oil with vinegar, garlic and peanuts, sold by weight from the cold counter.", recipe: "3d695c6d-26b4-81c4-b73c-d9b0ef53c0ce" },
    { name: "Garlic pork belly slices", zh: "蒜泥白肉", line: "Boiled belly cut into wide thin slices and dressed with pounded garlic and sweetened soy sauce.", recipe: "3d695c6d-26b4-81d0-8cb8-e0dafebedd74" },
    { name: "Smashed cucumber", zh: "拍黄瓜", line: "Cucumber broken open with the flat of the cleaver so garlic, vinegar and chilli oil soak into the cracks.", recipe: "dae482d1-cfed-4e44-9d66-deb04bb5b451" },
    { name: "Pickled vegetables", zh: "泡菜", line: "Radish, cabbage and long beans soured in a water-sealed jar, sold by the ladle to start a jar at home." },
    { name: "Douhua", zh: "豆花", line: "Just-set bean curd scooped into a bowl with chilli oil, soy and preserved vegetable, eaten standing at the stall." },
  ],
  wok: [
    { name: "Twice-cooked pork", zh: "回锅肉", line: "The dish a home cook is judged by: pork boiled, sliced thin, then fried with doubanjiang until the edges curl.", recipe: "3d695c6d-26b4-8178-93d0-edd89d8e0624" },
    { name: "Mapo tofu", zh: "麻婆豆腐", line: "Tofu simmered in chilli-bean paste with minced meat and a heavy dusting of ground Sichuan pepper at the end.", recipe: "cc9ed737-40c0-4fe8-bfb8-f144095ce03a" },
    { name: "Fish-fragrant shredded pork", zh: "鱼香肉丝", line: "Pork, wood ear and carrot in the pickled-chilli sauce that was built for fish and is used on everything but fish.", recipe: "3d695c6d-26b4-81b3-8ecb-fc178b041270" },
    { name: "Kung pao chicken", zh: "宫保鸡丁", line: "Diced chicken with peanuts and dried chillies in the sweet-sour sauce Sichuan cooks call lychee flavour.", recipe: "3d695c6d-26b4-8118-bee8-eaa7e34f8dca" },
    { name: "Water-boiled beef", zh: "水煮牛肉", line: "Beef poached in a red broth over bean sprouts, finished by pouring smoking oil over the chilli and pepper on top.", recipe: "3d695c6d-26b4-81e3-952e-ff38cf2681ef" },
    { name: "Fish-fragrant aubergine", zh: "鱼香茄子", line: "Aubergine fried until it collapses, then folded into the same pickled chilli, vinegar and sugar sauce.", recipe: "3d695c6d-26b4-8148-82fa-d10682e45427" },
    { name: "Dry-fried green beans", zh: "干煸四季豆", line: "Beans fried without liquid until the skins blister, then tossed with minced pork and preserved vegetable.", recipe: "3d695c6d-26b4-81b4-9d38-fd4c287d8d36" },
    { name: "Hot-and-sour potato slivers", zh: "酸辣土豆丝", line: "Potato cut to matchsticks, rinsed of its starch and fried two minutes with vinegar and dried chilli so it stays crisp.", recipe: "3d695c6d-26b4-81a4-8d25-cf7b3fb702e3" },
  ],
  tower: [
    { name: "Chuanchuan xiang", zh: "串串香", line: "Hotpot on skewers: you take what you want from the fridge, boil it in the red pot and pay by the stick." },
    { name: "Bobo chicken", zh: "钵钵鸡", line: "Cold skewers of chicken and vegetables steeped in a crock of chilli oil and Sichuan pepper, eaten at room temperature." },
    { name: "Chongqing chilli chicken", zh: "辣子鸡", line: "Chicken fried hard and buried in a wok of dried chillies, from the Gele hills; you hunt for the meat.", recipe: "3d695c6d-26b4-81db-a77d-dc1c9b4db7ec" },
    { name: "Málà rabbit heads", zh: "麻辣兔头", line: "Braised rabbit heads taken apart with the fingers, a Chengdu habit no other province picked up." },
    { name: "Mao cai", zh: "冒菜", line: "One person's hotpot: a basket of ingredients dipped in the shop's broth and tipped into a single bowl." },
    { name: "Intestine noodles", zh: "肥肠粉", line: "Sweet-potato noodles in a red broth with braised pork intestine, eaten standing at a lane counter for breakfast." },
  ],

  // ---------- Jiangnan ----------
  bao: [
    { name: "Xiaolongbao", zh: "小笼包", line: "Eighteen pleats around pork and a cube of jellied stock that melts to soup in the steamer; lift, bite, drink." },
    { name: "Pork bun", zh: "鲜肉包", line: "The big yeasted breakfast bun, one to a hand, sold out of the top basket before seven in the morning." },
    { name: "Greens and pork bun", zh: "菜肉包", line: "Chopped bok choy with a little pork, the bun families buy by the bagful on the way to school." },
    { name: "Red bean bun", zh: "豆沙包", line: "Sweet bean paste in the same dough, marked with a dot of red so it is not mistaken for the meat ones." },
    { name: "Crab-roe xiaolongbao", zh: "蟹粉小笼", line: "The autumn version, its filling stirred with roe and fat picked out of hairy crabs that morning." },
    { name: "Shengjian buns", zh: "生煎馒头", line: "Thick-skinned buns fried in a flat pan until the bottoms crust, scattered with sesame and scallion; Shanghai's." },
    { name: "Little wontons", zh: "小馄饨", line: "Skins so thin the pork shows through, dropped into clear broth with dried shrimp and shreds of egg." },
  ],
  crab: [
    { name: "Steamed hairy crab", zh: "清蒸大闸蟹", line: "Tied with straw, steamed fifteen minutes with perilla, and eaten with ginger, black vinegar and warmed wine." },
    { name: "Drunken crab", zh: "醉蟹", line: "Raw crab cured for days in Shaoxing wine, salt and spices and eaten cold; a Suzhou household's autumn jar." },
    { name: "Crab roe with tofu", zh: "蟹粉豆腐", line: "Roe and fat picked out of the shells and simmered with soft tofu until the whole bowl turns orange." },
    { name: "Crab-fat rice", zh: "秃黄油拌饭", line: "Nothing but roe and fat cooked in lard and poured over hot rice; several crabs go into one bowl." },
    { name: "Crab-roe noodles", zh: "蟹粉面", line: "The picked roe dressed over plain noodles, which is how a Suzhou shop sells crab to someone eating alone." },
  ],
  lotus: [
    { name: "Osmanthus sticky-rice lotus root", zh: "桂花糯米藕", line: "Root stuffed with glutinous rice, simmered with rock sugar and osmanthus, sliced cold to open a Hangzhou meal." },
    { name: "Lotus-leaf steamed pork", zh: "荷叶粉蒸肉", line: "Pork rolled in toasted rice meal, wrapped in a lotus leaf and steamed until the leaf has scented the meat." },
    { name: "Stir-fried lotus root", zh: "清炒藕片", line: "Lacy slices rinsed of starch and fried two minutes with a little vinegar so they stay crisp." },
    { name: "Lotus seed and white fungus soup", zh: "莲子银耳羹", line: "Seeds and fungus stewed into a thin sweet soup, cooked slowly in the morning and eaten warm or cold." },
    { name: "Lotus root starch", zh: "藕粉", line: "Powdered root stirred into boiling water until it turns clear and thick, the bowl given to children and invalids." },
  ],
  wine: [
    { name: "Jiafan, or huadiao", zh: "加饭酒·花雕", line: "The cellar's main wine: extra rice in the mash, years in a sealed urn, warmed in a pewter pot to drink." },
    { name: "Yuanhong", zh: "元红酒", line: "The dry, lighter yellow wine, named for the red paint on its urns and drunk young with everyday food." },
    { name: "Shanniang", zh: "善酿酒", line: "Fermented with aged wine in place of water, which is why it comes out darker and sweeter than the rest." },
    { name: "Xiangxue", zh: "香雪酒", line: "The sweet one, fermented with spirit so the ferment stops early; poured at the end of a crab meal." },
    { name: "Daughter's red", zh: "女儿红", line: "A batch buried the year a daughter is born and dug up for her wedding; the same wine, kept far longer." },
    { name: "Wine lees", zh: "酒糟", line: "What is left in the press, kept as a seasoning for drunken chicken, drunken shrimp and the cold lees dishes of summer." },
  ],
  rivermarket: [
    { name: "Smoked fish", zh: "熏鱼", line: "Carp steaks fried hard and steeped in a sweet spiced sauce, sold cold from the cooked-food counter by the steps." },
    { name: "Sauced duck", zh: "酱鸭", line: "Duck braised in soy, sugar and wine and hung at the stall, chopped on the board while you wait." },
    { name: "Lees-cured cold dishes", zh: "糟货", line: "Chicken feet, broad beans and pork tripe steeped in wine-lees brine and eaten cold through the summer." },
    { name: "Qingtuan", zh: "青团", line: "Glutinous rice dumplings coloured green with mugwort and filled with bean paste, made in the weeks around Qingming." },
    { name: "Zongzi", zh: "粽子", line: "Glutinous rice with pork belly or bean paste wrapped in bamboo leaves and boiled by the bucket before the Dragon Boat festival." },
    { name: "Fried stinky tofu", zh: "臭豆腐", line: "Tofu steeped in an old brine, fried black and crisp at the stall and eaten with chilli sauce; Shaoxing's own." },
  ],
  riverside: [
    { name: "West Lake vinegar fish", zh: "西湖醋鱼", line: "A whole grass carp poached and dressed in a sweet-sour sauce, on Hangzhou menus since the Song dynasty." },
    { name: "Dongpo pork", zh: "东坡肉", line: "Squares of belly braised for hours in soy, sugar and wine until the fat trembles; named for the poet-governor Su Dongpo." },
    { name: "Longjing shrimp", zh: "龙井虾仁", line: "River shrimp shelled by hand and fried with fresh Dragon Well leaves and a spoon of the tea." },
    { name: "Squirrel mandarin fish", zh: "松鼠鳜鱼", line: "Mandarin fish scored deep and fried so the cuts curl open, then covered in sweet-sour sauce; Suzhou's banquet dish." },
    { name: "Beggar's chicken", zh: "叫花鸡", line: "A whole chicken wrapped in lotus leaves and clay and baked until the clay is cracked open at the table." },
    { name: "Steamed mandarin fish", zh: "清蒸鳜鱼", line: "The day's fish steamed with ginger and scallion and finished with hot oil, the test of a kitchen's timing." },
  ],
  jnhome: [
    { name: "Red-braised pork", zh: "红烧肉", line: "Belly cut into cubes and braised in soy sauce, rock sugar and yellow wine until it is dark and glossy.", recipe: "5c80c042-ed56-4ca8-9b3e-2d50329c52f3" },
    { name: "Steamed whole fish", zh: "清蒸鱼", line: "A fish from the canal steamed eight minutes with ginger and scallion and finished with hot oil and soy." },
    { name: "Salt pork and bamboo shoot soup", zh: "腌笃鲜", line: "Cured pork, fresh pork and spring bamboo shoots simmered slowly into a milky soup; cooked only in spring." },
    { name: "Oil-braised bamboo shoots", zh: "油焖春笋", line: "Shoots cut into wedges and cooked down in oil, soy and sugar until they brown at the edges." },
    { name: "Steamed egg custard", zh: "蒸蛋羹", line: "Beaten egg and warm water steamed smooth in a bowl over the rice pot, the dish made for the children." },
    { name: "Stir-fried greens", zh: "清炒青菜", line: "Whatever green came back from the market, cooked two minutes with garlic in the second wok." },
  ],
  // A landmark cooks nothing; what it keeps is what is sold and eaten on the spot.
  stonebridge: [
    { name: "Dingsheng cake", zh: "定胜糕", line: "Pink steamed rice cake pressed in a wooden mould, sold at the foot of the bridge and eaten warm." },
    { name: "Rice-wine dumplings", zh: "酒酿圆子", line: "Small glutinous balls in sweet fermented rice wine, ladled hot from a pot at the end of the bridge." },
    { name: "Plum blossom cake", zh: "梅花糕", line: "Batter baked in flower-shaped moulds over charcoal with bean paste inside, sold from a cart on the steps." },
    { name: "Sweet red bean congee", zh: "糖粥", line: "Red bean congee carried round in a hawker's shoulder pot, known in Suzhou by its clapper before its smell." },
    { name: "Smoked bean tea", zh: "熏豆茶", line: "Salted tea with smoked green soybeans, orange peel and sesame, poured for anyone who sits down by the water." },
  ],
  teahill: [
    { name: "Pre-Qingming Longjing", zh: "明前龙井", line: "A bud and a single leaf picked before early April and pan-fired by hand the same day; the year's prize." },
    { name: "Yuqian Longjing", zh: "雨前龙井", line: "Picked in the weeks after, a bigger leaf and a stronger cup, and what the teahouses pour all summer." },
    { name: "Jiuqu Hongmei", zh: "九曲红梅", line: "The black tea of the same hills, rolled into dark curls; the cup Hangzhou drinks in winter." },
    { name: "Longjing shrimp", zh: "龙井虾仁", line: "Fresh leaves go down the hill to the restaurants, where they are fried with river shrimp and a little of the tea." },
  ],

  // ---------- Northern China ----------
  knifenoodle: [
    { name: "Knife-shaved noodles", zh: "刀削面", line: "Shaved off a slab of dough straight into the boiling pot with a curved blade, each flake thick-spined and thin-edged." },
    { name: "Hand-pulled noodles", zh: "拉面", line: "A rope doubled and pulled again and again into a bundle of strands, counted by how many pulls it took." },
    { name: "Belt noodles", zh: "裤带面", line: "Rolled and cut as wide as a belt, one noodle filling the bowl; Shaanxi's, eaten under chilli and hot oil." },
    { name: "Cat's ears", zh: "猫耳朵", line: "Pieces of dough pressed with the thumb into curls that hold sauce, the shape children are set to make." },
    { name: "Zhajiang noodles", zh: "炸酱面", line: "Beijing's bowl: fried soybean paste with pork, with shredded cucumber and radish stirred in at the table." },
    { name: "Gravy noodles", zh: "打卤面", line: "Noodles under a thick starch-bound gravy of pork, egg and wood ear, made for birthdays and for guests." },
  ],
  mantou: [
    { name: "Mantou", zh: "馒头", line: "Yeasted wheat dough kneaded hard, shaped into a dome and steamed white, springy and faintly sweet." },
    { name: "Flower rolls", zh: "花卷", line: "The same dough rolled with oil, salt and scallion and twisted, so the layers show when it is pulled apart." },
    { name: "Meat baozi", zh: "肉包子", line: "Mantou dough closed around pork and cabbage, pleated and steamed in the same towers of bamboo baskets." },
    { name: "Sugar triangles", zh: "糖三角", line: "Brown sugar folded into three corners of dough; it comes out molten and has burnt every child once." },
    { name: "Jujube buns", zh: "枣馍", line: "Dough coiled around red dates and steamed for festivals and for the offering table at New Year." },
    { name: "Silver-thread rolls", zh: "银丝卷", line: "Fine strands of dough wrapped in a plain sheet and steamed, so the roll opens into threads; Shandong's." },
  ],
  vinegar: [
    { name: "Aged Shanxi vinegar", zh: "山西老陈醋", line: "Sorghum fermented, smoked, and then aged in courtyard jars for a year or more until it is black and thick." },
  ],
  roastduck: [
    { name: "Beijing roast duck", zh: "北京烤鸭", line: "Air pumped under the skin, glazed with maltose, dried a day, roasted over fruit wood and carved into about a hundred slices." },
    { name: "Duck-bone soup", zh: "鸭架汤", line: "The carcass boiled milky with cabbage and tofu and brought to the table at the end of the meal." },
    { name: "Mustard duck webs", zh: "芥末鸭掌", line: "Cold duck feet dressed with mustard, one of the small dishes eaten while the duck is still in the oven." },
    { name: "Seared duck hearts", zh: "火燎鸭心", line: "Hearts flashed over a high flame with scallion, a plate the old shops keep for their regulars." },
  ],
  bing: [
    { name: "Scallion pancake", zh: "葱油饼", line: "Dough rolled with oil and scallion, coiled, flattened and fried on the griddle until the layers separate." },
    { name: "Sesame shaobing", zh: "芝麻烧饼", line: "Layered rounds stuck with sesame and baked against the wall of a barrel oven, then split and filled at breakfast." },
    { name: "Roujiamo", zh: "肉夹馍", line: "A griddle-baked bun split and packed with pork braised in a spiced master stock; Xi'an's, eaten with both hands." },
    { name: "Spring pancakes", zh: "春饼", line: "Thin rounds steamed in pairs and pulled apart to wrap shredded vegetables and egg at the start of spring." },
    { name: "Guokui", zh: "锅盔", line: "A flat loaf as thick as a board that keeps for a week; what a Shaanxi farmer carried into the fields." },
    { name: "Sugar shaobing", zh: "糖火烧", line: "Dough layered with brown sugar and sesame paste and baked dark; Beijing's, sold from the same counter." },
  ],
  northmarket: [
    { name: "Soured cabbage", zh: "酸菜", line: "Whole cabbages packed into a crock under a stone and left to sour for weeks; the north's winter vegetable." },
    { name: "Preserved vegetables", zh: "酱菜", line: "Radish, cucumber and gourd kept in soy-bean paste; Beijing's Liubiju has sold them since 1530." },
    { name: "Sauced pork knuckle", zh: "酱肘子", line: "Pork simmered in soy, sugar and spices until it falls apart, sold cold and sliced off the bone at the counter." },
    { name: "Douhua with gravy", zh: "豆腐脑", line: "Soft curd ladled into a bowl under a thick gravy of pork and wood ear, breakfast at the market gate." },
    { name: "Youtiao", zh: "油条", line: "Lengths of dough pulled long and fried, eaten with hot soy milk while the shopping is still in the basket." },
  ],
  skewers: [
    { name: "Lamb skewers", zh: "羊肉串", line: "Cubes of lamb with a piece of fat between them, shaken with cumin, chilli flakes and salt over the charcoal trough." },
    { name: "Grilled kidneys", zh: "烤腰子", line: "Split, salted and grilled fast so they stay soft, the plate ordered late that keeps the beer moving." },
    { name: "Grilled aubergine", zh: "烤茄子", line: "Split down the middle, cooked soft over the coals and heaped with garlic, chilli and coriander." },
    { name: "Grilled chives", zh: "烤韭菜", line: "A bundle laid straight on the grill until the ends char, and the cheapest thing on the board." },
    { name: "Grilled fish", zh: "烤鱼", line: "A whole fish scored, spiced and cooked over the trough, carried to the table on its own tray." },
    { name: "Grilled mantou slices", zh: "烤馒头片", line: "Yesterday's steamed bread sliced, brushed with oil and cumin and toasted at the cool end of the grill." },
  ],
  wintertable: [
    { name: "Pork, cabbage and glass noodles", zh: "猪肉白菜炖粉条", line: "One pot for the table: belly pork stewed with cabbage from the pile by the wall and sweet-potato noodles." },
    { name: "Boiled dumplings", zh: "饺子", line: "Folded by every hand in the house and boiled in batches, with vinegar and raw garlic beside each bowl." },
    { name: "Chicken with mushrooms", zh: "小鸡炖蘑菇", line: "The north-east's pot: chicken stewed slowly with dried hazel mushrooms until the broth goes dark." },
    { name: "Soured cabbage with pork", zh: "酸菜汆白肉", line: "Sour cabbage shredded fine and simmered with thin-sliced belly pork and glass noodles." },
    { name: "Millet porridge", zh: "小米粥", line: "Yellow millet boiled soft, the bowl that finishes the meal and the one given to anyone who is ill." },
    { name: "Mantou", zh: "馒头", line: "Steamed bread on the table from the start, torn and dipped into the braising juices." },
  ],
  dumpling: [
    { name: "Pork and cabbage dumplings", zh: "猪肉白菜饺", line: "The house filling: pork, cabbage squeezed dry, ginger and scallion, pleated shut and boiled with water added three times." },
    { name: "Chive and egg dumplings", zh: "韭菜鸡蛋饺", line: "Scrambled egg with chives and a few dried shrimp, the filling ordered when no meat is wanted." },
    { name: "Lamb and carrot dumplings", zh: "羊肉胡萝卜饺", line: "Minced lamb with grated carrot and cumin, a Muslim-quarter filling that spread across the whole north." },
    { name: "Three-fresh dumplings", zh: "三鲜饺", line: "Pork, river shrimp and chives together in one wrapper, the filling kept for a holiday table." },
    { name: "Pan-fried dumplings", zh: "煎饺", line: "Set in a flat pan with a little water and fried until the bottoms crust and the tops stay soft.", recipe: "d00d4143-db1b-4d04-bb94-6b0e43d6bb55" },
    { name: "Steamed dumplings", zh: "蒸饺", line: "Pleated and set in bamboo tiers instead of the pot, which leaves the skins chewier." },
    { name: "Wontons", zh: "馄饨", line: "Thin skins folded around a little pork and dropped into clear broth with seaweed and dried shrimp." },
  ],
  griddle: [
    { name: "Hand-rolled noodles", zh: "手擀面", line: "Dough rolled out on the board into a sheet, folded and cut by hand, straight into the wok's boiling water." },
    { name: "Vinegar-slipped cabbage", zh: "醋溜白菜", line: "Cabbage stalks fried hard with dried chilli and a splash of aged vinegar poured down the side of the wok." },
    { name: "Dough-drop soup", zh: "疙瘩汤", line: "Flour flicked with water into small lumps and boiled with tomato and egg, for a night when nobody wants to cook." },
    { name: "Potato slivers with vinegar", zh: "醋溜土豆丝", line: "Potato cut to matchsticks and fried two minutes with vinegar and chilli; the northern version, sour rather than numbing." },
    { name: "Griddle cakes", zh: "烙饼", line: "Layered pancakes cooked dry on the flat bottom of the same wok and torn up to go with the stew." },
    { name: "Beef and scallion pancake rolls", zh: "牛肉卷饼", line: "Beef fried with onion and scallion and rolled into a griddle pancake, eaten in the hand at the yard table.", recipe: "e52d2c43-f84d-4aa1-a2af-4e6867e319bd" },
  ],
  // The lane cooks nothing of its own; the carts and hole-in-the-wall counters along it do.
  hutong: [
    { name: "Tanghulu", zh: "糖葫芦", line: "Hawthorns skewered and dipped in boiled sugar, carried down the lane on a straw post through the winter." },
    { name: "Roast sweet potato", zh: "烤红薯", line: "Sweet potatoes turned in an oil-drum stove at the lane's mouth and sold hot by weight from November." },
    { name: "Chaogan", zh: "炒肝", line: "Pork liver and intestine in a thick garlicky gravy, drunk from the rim of the bowl without a spoon." },
    { name: "Douzhi and jiaoquan", zh: "豆汁儿·焦圈", line: "Sour fermented mung-bean drink with a fried dough ring, the Beijing breakfast outsiders rarely finish." },
    { name: "Luzhu", zh: "卤煮火烧", line: "Offal and flatbread simmered in one pot and chopped into a bowl, the cheapest hot meal on the lane." },
  ],
  wheat: [
    { name: "New-wheat noodles", zh: "新麦面条", line: "The first flour of the year is cut into noodles and eaten with garlic and vinegar on the threshing floor." },
    { name: "Mantou", zh: "馒头", line: "Most of the flour goes to steamed bread, a basketful at a time, to feed the household through the year." },
    { name: "Dumplings", zh: "饺子", line: "The wrappers the winter's festivals need; a sack of flour is measured against how many they will make." },
    { name: "Griddle cakes", zh: "烙饼", line: "Flat layered breads cooked at the field kitchen and carried out wrapped in a cloth while the cutting goes on." },
    { name: "Mung bean soup", zh: "绿豆汤", line: "Carried to the threshing floor in a bucket and drunk warm, which is what the harvest is actually thirsty for." },
  ],

  // ---------- Xinjiang ----------
  kebab: [
    { name: "Lamb kawap", zh: "烤羊肉串", line: "Cubes of lamb threaded with a piece of tail fat between them, dusted with cumin and chilli as the skewers turn." },
    { name: "Rib kawap", zh: "烤羊排", line: "Whole ribs salted and laid over the coals, cut apart at the table and eaten with torn nan." },
    { name: "Kidney kawap", zh: "烤腰子", line: "Split kidneys grilled quickly so they stay soft inside, ordered by the pair late in the evening." },
    { name: "Tonur-roasted lamb", zh: "馕坑肉", line: "Chunks of lamb hooked inside the bread oven after the nan comes out and roasted in the falling heat." },
  ],
  naan: [
    { name: "Big thin nan", zh: "大馕", line: "A round the width of a cartwheel, pressed thin in the middle, stamped with a chekich and baked against the oven wall." },
    { name: "Girde nan", zh: "窝窝馕", line: "Small and thick with a deep dimple, the everyday loaf of Hotan, torn up and softened in tea." },
    { name: "Oil nan", zh: "油馕", line: "Dough worked with mutton fat so it stays soft for days, which is what a family takes on a journey." },
    { name: "Sesame nan", zh: "芝麻馕", line: "Brushed with onion water and covered in sesame, the round sold hot at the roadside window." },
    { name: "Meat nan", zh: "肉馕", line: "Diced lamb and onion sealed inside the dough before it goes on the wall, and eaten as a meal on its own." },
    { name: "Sweet nan", zh: "甜馕", line: "Made with grape juice or sugar in the dough, baked for festivals and for the children." },
  ],
  polo: [
    { name: "Lamb polo", zh: "羊肉抓饭", line: "Lamb browned in the kazan with onion and a great deal of carrot, rice laid on top and steamed until it takes the fat." },
    { name: "Wedding polo", zh: "婚宴抓饭", line: "The same pot made for a whole street: raisins, chickpeas and quince stirred in, a piece of lamb on every bowl." },
    { name: "Vegetable polo", zh: "素抓饭", line: "Carrot, onion and raisins without the meat, cooked when there is no lamb in the house." },
    { name: "Pilaz salad", zh: "皮辣红", line: "Onion, tomato and green chilli cut thin and salted, set beside the rice to cut the fat." },
    { name: "Yoghurt", zh: "酸奶", line: "Set in bowls and eaten with the rice or straight after it, sharp enough to answer a plate of fat lamb." },
  ],
  laghman: [
    { name: "Laghman", zh: "拌面", line: "One rope of dough swung into a single long noodle, boiled, and topped with lamb, tomato, pepper and onion from the wok." },
    { name: "Fried-lamb laghman", zh: "过油肉拌面", line: "The topping made with lamb slices passed through hot oil first, the version most shops are judged on." },
    { name: "Fried laghman", zh: "炒面", line: "Noodles and topping put back into the wok together so the ends catch and crisp." },
    { name: "Paozhangzi", zh: "炮仗子", line: "The noodles cut short with scissors and fried with minced lamb and tomato, and named after firecrackers." },
    { name: "Suoman soup", zh: "汤饭", line: "Dough torn into small squares and boiled with lamb and vegetables into a thick soup for cold days." },
    { name: "Big-plate chicken", zh: "大盘鸡", line: "Chicken stewed with potato, pepper and chilli and poured over belt-wide noodles; invented in Shawan in the 1980s." },
  ],
  bazaar: [
    { name: "Hami melon", zh: "哈密瓜", line: "Cut into crescents at the stall and sold by the slice; the desert's cold nights are what make it sweet." },
    { name: "Turpan raisins", zh: "吐鲁番葡萄干", line: "Dried green in latticed mud-brick houses on the roofs and sold from open sacks by the scoop." },
    { name: "Walnut sweet bar", zh: "玛仁糖", line: "Walnuts, raisins and sesame set in grape syrup, pressed into a block and cut off with a heavy knife." },
    { name: "Samsa", zh: "烤包子", line: "Squares of pastry filled with diced lamb, onion and cumin and stuck to the oven wall behind the stalls." },
    { name: "Yoghurt with shaved ice", zh: "酸奶", line: "Poured from the crock into a bowl with ice shaved off a block, sold beside the melons in summer." },
    { name: "Pomegranate juice", zh: "石榴汁", line: "Pressed at the stall a glass at a time in autumn, when the Kashgar pomegranates come in." },
    { name: "Fresh figs", zh: "无花果", line: "Sold in leaf-lined baskets and eaten the same day, because they are too soft to travel." },
  ],
  grapes: [
    { name: "Seedless white grapes", zh: "无核白葡萄", line: "Turpan's green grape, eaten straight off the trellis over the table all through the summer." },
    { name: "Raisins", zh: "葡萄干", line: "The same grapes dried in the latticed house on the roof, kept for winter and served with tea." },
    { name: "Nan and tea", zh: "馕与茶", line: "What is set on the low table whenever a guest arrives, before anything is asked or cooked." },
    { name: "Dried fruit plate", zh: "干果盘", line: "Apricots, mulberries, figs and walnuts in small dishes: the first thing offered and the last thing cleared." },
  ],
  // The field and the road: what is eaten where the food is grown or carried, not cooked.
  oasis: [
    { name: "Hami melon", zh: "哈密瓜", line: "Cut open at the channel edge at midday and eaten off the knife by whoever is working the strip." },
    { name: "New-wheat nan", zh: "馕", line: "The wheat of these fields goes to the tonur; a family bakes fifty rounds at a time from one harvest." },
    { name: "Polo from these rows", zh: "抓饭", line: "The yellow carrots and onions grown here go into the kazan under the rice, which is what they are for." },
    { name: "Raisins", zh: "葡萄干", line: "Grapes off the trellis rows are hung in the latticed house on the roof and come out green." },
    { name: "Dried melon strips", zh: "甜瓜干", line: "Melon cut into strips and dried on frames, kept for the winter when nothing fresh is left." },
  ],
  caravan: [
    { name: "Road nan", zh: "馕", line: "Baked hard so it keeps for weeks and softened in tea at the fire; what every load on this road carried." },
    { name: "Brick tea", zh: "砖茶", line: "Tea pressed into slabs that survive a camel's back, boiled at the stop and once accepted as money." },
    { name: "Dried fruit and nuts", zh: "干果", line: "Raisins, apricots and walnuts out of the sacks: food that travels well and is also the cargo." },
    { name: "Boiled mutton", zh: "手抓肉", line: "A sheep boiled plain in a cauldron and pulled apart by hand when a caravan stays the night." },
  ],
  tianshan: [
    { name: "Milk tea", zh: "奶茶", line: "Brick tea boiled with fresh milk and salt in the summer pasture and drunk from a bowl all day." },
    { name: "Kurut", zh: "奶疙瘩", line: "Sour milk drained, salted and dried hard on the tent roof, kept as the herders' cheese for winter." },
    { name: "Milk skin", zh: "奶皮子", line: "The skin lifted off boiled milk and dried into a disc, eaten with bread and with tea." },
    { name: "Boiled high-pasture mutton", zh: "清炖羊肉", line: "Sheep grazed on the snowmelt grass, boiled with onion and salt, and the broth drunk after the meat." },
  ],
  chaikhana: [
    { name: "Bowl tea", zh: "砖茶", line: "Black tea broken off the brick and boiled in a copper pot, poured into bowls and refilled all afternoon." },
    { name: "Milk tea", zh: "奶茶", line: "Tea boiled with milk and salt, the mountain version, drunk with bread crumbled into the bowl." },
    { name: "Nan", zh: "馕", line: "Torn and set on the cloth before anything else, and a dry round is softened in the tea." },
    { name: "Walnuts and raisins", zh: "核桃·葡萄干", line: "Set out in small dishes with the pot and kept filled for as long as the talking goes on." },
    { name: "Suoman soup", zh: "汤饭", line: "The one hot dish at midday: dough squares boiled with lamb and vegetables for whoever is still sitting." },
  ],
  xjhome: [
    { name: "Manta", zh: "薄皮包子", line: "Thin-skinned parcels of diced lamb, onion and pepper, steamed in stacked tiers over the kazan." },
    { name: "Chüchürä", zh: "曲曲", line: "Small dumplings pinched by the handful and boiled in lamb broth, eaten with a spoon from the bowl." },
    { name: "Suoman", zh: "揪片子", line: "Dough torn into small squares, boiled, and then fried with lamb, tomato and pepper." },
    { name: "Home laghman", zh: "拉条子", line: "The same pulled noodles as the shop's, made on the board under the vines when the family is large." },
    { name: "Lamb broth", zh: "羊肉汤", line: "Lamb boiled plain with onion and a little salt; the broth is drunk and the meat pulled apart by hand." },
  ],
  feast: [
    { name: "Polo", zh: "抓饭", line: "The great platter set down in the middle once everyone is seated, with a piece of lamb on each bowl." },
    { name: "Kawap", zh: "烤羊肉串", line: "Skewers carried from the grill in bunches and laid on the cloth for whoever can reach them." },
    { name: "Whole roast sheep", zh: "烤全羊", line: "A sheep roasted in the tonur for a wedding, carried in on a board and cut apart in front of the guests." },
    { name: "Manta", zh: "薄皮包子", line: "Steamed tiers brought out between the grilled things, while the polo is still under its lid." },
    { name: "Nan", zh: "馕", line: "Broken and placed on the cloth first; nothing else is set down before the bread is." },
    { name: "Melon crescents", zh: "哈密瓜", line: "Cut and brought last, when the fat has been eaten and the tea is going round again." },
  ],
};
