/** Short, room-specific discoveries. Action controls are bound to effects already in the painting. */
export const ROOM_DISCOVERIES: Record<string, [string, string]> = {
  noodle_shop: ["From dough to noodles", "Stretch, fold and stretch again. The long strands go straight into the broth; the bowl is finished with its own seasoning."],
  teahouse: ["Lift the gaiwan lid", "The lid holds the leaves back as you sip. Tea, a little shade and a seat with neighbours make this an afternoon stop."],
  market: ["Follow the ingredients", "Chillies, garlic and greens leave these stalls for the village kitchens. Open a stand below to follow its ingredient into a dish."],
  home_kitchen: ["Before the wok heats", "Chop the vegetables and ready the seasonings first. Once the wok is hot, the cooking moves quickly."],
  tower: ["Look towards supper", "Below the tower, kitchens, markets and river crossings connect the village. The lanterns mark the places where the evening gathers."],
  bao_shop: ["Inside the steamer", "Pleated dough holds the filling. Steam cooks the bun gently while the bamboo baskets let moisture escape."],
  stone_bridge: ["Food travels by water", "Boats bring produce to the steps; the bridge links the kitchens on either bank. Follow the canal back to the market."],
  crab_pond: ["At the crab table", "Crab is served with ginger and vinegar. Small dishes and patient picking make this a meal to linger over."],
  jiangnan_home: ["One family, several pots", "A steamer, a braising pot and a board of greens share the kitchen. Their different cooking times meet at one family meal."],
  lotus_garden: ["Root, seed and leaf", "Lotus offers more than a flower: crisp roots, seeds for sweet or savoury dishes, and broad leaves for wrapping food."],
  rice_wine: ["Rice becomes wine", "Cooked rice, fermentation and time lead to rice wine. The jars are part of the kitchen as well as the cellar."],
  river_market: ["From boat to basket", "Fish, greens and lotus root arrive at the water's edge. The canal is part of the market's daily supply route."],
  riverside_restaurant: ["Build a shared meal", "A fish, a braise, soup and greens give the table different textures. Everyone takes a little from the shared dishes."],
  tea_hill: ["From leaf to cup", "Tender leaves are picked, then heated to stop oxidation. The work in the pan matters as much as the work on the hill."],
  kebab_grill: ["Cumin meets charcoal", "Small pieces of lamb and fat cook on skewers. Cumin and chilli season the surface as the skewers turn over the coals."],
  naan_bakery: ["Bread on the oven wall", "The baker presses the rounds onto the hot tonur wall. The stamped centre helps the bread keep its shape."],
  polo_kitchen: ["Layers in the kazan", "Carrots, meat and rice cook together in the deep pot. The rice takes up the cooking liquid and its flavour."],
  laghman_shop: ["A rope becomes a bowl", "The dough is stretched into long noodles, then served with a topping of vegetables and meat from the wok."],
  oasis_bazaar: ["Pack a travelling meal", "Nan, dried fruit and nuts sit beside fresh melons and spices. Some foods are for today; others travel well."],
  grape_courtyard: ["Shade that bears fruit", "The grape arbor shades the courtyard and brings fruit within reach. Tea, bread and conversation gather underneath."],
  oasis_field: ["Follow the channel", "Water reaches the planted strip through irrigation channels. The green fields show how closely the harvest depends on that water."],
  chaikhana: ["Tea at a low table", "Bowls of tea, nan and dried fruit turn a shaded platform into a place to sit and talk."],
  xj_home: ["Dough, hearth and kazan", "Bread, noodles and rice need different tools. The board, oven and deep pot give this kitchen several ways to feed a family."],
  caravan_stop: ["Food for the next stage", "Tea offers a pause; bread and dried fruit can go on the journey. The table is where travellers rest and exchange news."],
  tianshan: ["Mountains feed the fields", "Snowmelt flows down towards the oasis. Follow the water from the mountains to the channels beside the crops."],
  evening_feast: ["Make room at the table", "Bread, rice, skewers and fruit are set out to share. The courtyard becomes a dining room when everyone gathers."],
  skewer_courtyard: ["Around the charcoal", "The cook turns the skewers so each side meets the heat. Flatbread and small dishes round out the meal."],
  mantou_kitchen: ["A twist in the dough", "Plain mantou and folded huajuan start with dough. Shaping changes how the steamed bread pulls apart."],
  dumpling_house: ["Wrapper, filling, pleat", "Roll a wrapper, add a little filling and seal the edge. A good seal keeps the filling inside as the dumpling cooks."],
  winter_table: ["A meal for cold weather", "Cabbage, pork and dumplings fill the table. Stored vegetables and hot dishes carry the family through winter."],
  courtyard_kitchen: ["Several hands, one dinner", "Rolling, chopping and cooking happen side by side. The courtyard gives each task a little room."],
  hutong: ["Kitchens meet the lane", "Neighbours step outside with bowls, baskets and conversation. The lane connects the private kitchen to daily village life."],
  bing_stall: ["Bread on the griddle", "Contact with the hot surface browns the dough. Turning the bread cooks both sides while keeping the centre tender."],
  north_market: ["Stock the winter kitchen", "Cabbage, roots, flour and jars fill the stalls. These are ingredients that can become many meals."],
  noodle_workshop: ["Two ways to make a noodle", "Some dough is pulled into strands; some is shaved straight into a pot. The shaping changes the noodle's bite."],
  roast_duck: ["Wrap a little of everything", "Duck, scallion and sauce go into a thin pancake. Crisp skin, soft bread and fresh crunch meet in one bite."],
  vinegar_workshop: ["Give the jars time", "Grain is fermented and the vinegar is aged. A small bowl at the table can sharpen a rich dish or a dumpling."],
  wheat_harvest: ["Grain becomes dinner", "The harvested grain is threshed and milled. Its flour becomes the noodles, dumplings and breads in the northern village."],
};
