import type { WorldObject, Area } from './graph';
import { TURKEY_STORY_DEPTH } from './turkey-stories';

/** Optional story-card links follow ingredients and meals between rooms. */
export const TURKEY_NEXT: Record<string,string[]> = {
  simit:['teaGarden','kahvalti'], teaGarden:['teaHillTr','balikEkmek'],
  turkishCoffee:['sweetShop','teaGarden'], bazaar:['dolmaTr','oliveTr'],
  balikEkmek:['simit','mezeTr'], mangal:['pideTr','supperTr'],
  sweetShop:['turkishCoffee','yufkaTr'], pideTr:['mangal','yufkaTr'],
  yufkaTr:['kahvalti','pideTr'], dolmaTr:['bazaar','oliveTr'],
  kahvalti:['simit','teaGarden'], mezeTr:['oliveTr','balikEkmek'],
  oliveTr:['dolmaTr','mezeTr'], teaHillTr:['teaGarden','kahvalti'],
  supperTr:['yufkaTr','mangal'],
};

type Place = [id:string, name:string, zh:string, area:Area, x:number, z:number, prop:string, scene:string, emoji:string, tagline:string, blurb:string, food:string];
const places: Place[] = [
  ['simit','Simit by the ferry','Simitçi','istanbul',-31,-38,'turkeySimitCart','tr_simit','🥨','A sesame ring for the crossing.','Warm simit, cheese and tea are part of an ordinary Istanbul morning. Walk along the quay, stop at the cart, and watch the ferries connect the two shores.','simit'],
  ['teaGarden','Waterfront tea garden','Çay bahçesi','istanbul',-20,-38,'turkeyTeaGarden','tr_tea','🫖','Tea, backgammon and the Bosphorus.','A tea garden is a place to sit with friends and family. Tulip glasses are refilled, backgammon pieces move across the board, and conversation can last all afternoon.','tea'],
  ['turkishCoffee','Neighbourhood coffeehouse','Kahvehane','istanbul',-3.8,-35,'turkeyCoffee','tr_coffee','☕','A small cup and time to talk.','Finely ground coffee is heated in a cezve and served unfiltered in a small cup. The preparation belongs with the welcome: water, coffee and a visit that need not be hurried.','coffee'],
  ['bazaar','Istanbul market','Semt pazarı','istanbul',-20,-26,'bazaar','tr_market','🍅','Follow a basket from the market to supper.','Fresh produce markets sit alongside Istanbul’s covered shopping streets. Peppers, aubergines, tomatoes, olives and herbs connect these stalls with the kitchens nearby.','dolma'],
  ['balikEkmek','Fish at the quay','Balık ekmek','istanbul',-45,-38,'turkeyFish','tr_fish','🐟','Grilled fish and bread beside the water.','Istanbul’s waterfront is a place to eat as well as travel. Fish sandwiches, onions and greens meet ferry queues, fishermen and the changing light on the Bosphorus.','balik-ekmek'],
  ['mangal','Charcoal kitchen','Ocakbaşı','istanbul',-22,-13,'turkeyKebab','tr_kebab','🍢','Skewers turn above glowing coals.','At an ocakbaşı the charcoal hearth is part of the meal. Şiş, grilled peppers, bread, onion with sumac and a cool ayran are familiar companions. Regional kebab styles vary across Türkiye.','sis'],
  ['sweetShop','Baklava workshop','Baklavacı','anatolia',7,-26,'turkeyBaklava','tr_baklava','🍯','Thin pastry, butter and pistachios.','Gaziantep is closely associated with pistachio baklava. In the workshop, pastry is rolled thin, layered with butter and nuts, cut into portions and baked before syrup is added.','baklava'],
  ['pideTr','Pide and lahmacun oven','Pide fırını','anatolia',19,-12,'turkeyPide','tr_pide','🫓','The hot oven feeds the lane.','A boat-shaped pide holds its filling inside a raised rim. Lahmacun is a thin round with a minced meat, vegetable and herb topping, often eaten with parsley and lemon.','pide'],
  ['yufkaTr','Village bread courtyard','Yufka ve gözleme','anatolia',7,-12,'turkeyYufka','tr_yufka','🥖','Rolling pins, thin dough and shared work.','Yufka is rolled thin; it can become layered börek or folded gözleme with cheese, greens or another savoury filling. Making bread together turns preparation into a social activity.','borek'],
  ['dolmaTr','The dolma kitchen','Dolma ve sarma','aegean',-34,0,'turkeyDolma','tr_dolma','🫑','Fill a pepper, roll a leaf.','Dolma means filled; sarma means wrapped. Rice, herbs, vegetables and sometimes meat come together in recipes that vary by home and region. Olive-oil preparations are often served cool.','sarma'],
  ['kahvalti','The breakfast house','Kahvaltı','istanbul',-4,-24,'turkeyBreakfast','tr_breakfast','🍳','A long table of small morning plates.','Cheese, olives, tomatoes, cucumber, eggs, bread, honey and tea bring sweet and savoury tastes to breakfast. Families and friends linger over a spread that changes from region to region.','breakfast'],
  ['mezeTr','Aegean meze table','Meze sofrası','aegean',-38,-13,'turkeyMeze','tr_meze','🥗','Vegetables, yogurt and herbs to share.','Small plates invite everyone to try a little. Aubergine, yogurt, olive oil and fresh herbs sit alongside bread and warm dishes; the meal grows with the conversation.','meze'],
  ['oliveTr','Aegean olive grove','Zeytinlik','aegean',-47,0,'turkeyOliveGrove','tr_olive','🫒','Silver leaves above the harvest baskets.','The Aegean coast connects olive groves with everyday kitchens. Oil seasons vegetables, bread and fish. Table olives are cured before they become part of breakfast.','olive-oil'],
  ['teaHillTr','Black Sea tea terraces','Karadeniz çaylıkları','blacksea-tr',38,-34,'turkeyTeaHill','tr_tea_hill','🌿','Rainy hills supply the tea glass.','Around Rize, tea rows climb the green eastern Black Sea hills. Harvested leaves are processed into the black tea poured in homes, shops and tea gardens across Türkiye.','tea-leaves'],
  ['supperTr','Anatolian family supper','Akşam sofrası','anatolia',31,-12,'turkeySupper','tr_supper','🫕','Soup, bread, bulgur and a pot to share.','Everyday cooking belongs beside the famous street foods: lentil soup, bulgur pilaf, vegetable dishes and slow-cooked pots. Mantı brings small filled dumplings together with yogurt and spiced butter.','stew'],
];

export const TURKEY_CARD_ART: Record<string,string> = Object.fromEntries(places.map(p=>[p[0],p[11]]));
export const TURKEY_OBJECTS: WorldObject[] = places.map(([id,name,zh,area,x,z,prop,scene,emoji,tagline,blurb])=>({
  id,world:'middle-east',kind:'place',name,placeName:name,zh,area,pos:[x,z],prop,scene,emoji,tagline,blurb:blurb+"\n\n"+TURKEY_STORY_DEPTH[id],place:true,rot:0,
  elevation:id==='teaHillTr'?4.5:id==='yufkaTr'?1:id==='supperTr'?1.2:0,
  match:r=>r.place===id,
}));
// The stalls remain available inside the painted market, with Turkish names and relevant local links.
TURKEY_OBJECTS.push(
  {id:'spicesMe',world:'middle-east',kind:'flavour',name:'Sumac and pepper flakes',zh:'Sumak ve pul biber',emoji:'🌶️',area:'istanbul',pos:[-25.5,-28.6],prop:'none',hitOnly:true,parent:'bazaar',tagline:'Sour red berries, warm red pepper.',blurb:'Sumac brings a tart taste to onion salads; pul biber adds warmth to many dishes. Explore the charcoal counter to see how seasonings accompany the grill.',partners:['sumac','paprika','yogurt'],match:r=>r.core.some(i=>/sumac|paprika|cumin/.test(i))},
  {id:'sweets',world:'middle-east',kind:'dish',name:'Baklava and pistachios',zh:'Baklava ve fıstık',emoji:'🍯',area:'istanbul',pos:[-15.5,-28.6],prop:'none',hitOnly:true,parent:'bazaar',alias:'sweetShop',tagline:'',blurb:'',match:()=>false},
  {id:'tea',world:'middle-east',kind:'dish',name:'Tea and hospitality',zh:'Çay',emoji:'🫖',area:'istanbul',pos:[-19,-23.4],prop:'none',hitOnly:true,parent:'bazaar',alias:'teaGarden',tagline:'',blurb:'',match:()=>false},
  {id:'stall-olives',world:'middle-east',kind:'ingredient',name:'Olives and oil',zh:'Zeytin',emoji:'🫒',area:'istanbul',pos:[-14,-23.4],prop:'none',hitOnly:true,parent:'bazaar',alias:'oliveTr',tagline:'',blurb:'',match:()=>false},
  {id:'stall-nuts',world:'middle-east',kind:'ingredient',name:'Nuts and dried fruit',zh:'Kuruyemiş',emoji:'🥜',area:'istanbul',pos:[-24,-23.4],prop:'none',hitOnly:true,parent:'bazaar',alias:'sweetShop',tagline:'',blurb:'',match:()=>false},
  {id:'stall-lamps',world:'middle-east',kind:'landmark',name:'Tea sets and lamps',zh:'Çay takımları',emoji:'🪔',area:'istanbul',pos:[-20.5,-28.6],prop:'none',hitOnly:true,parent:'bazaar',alias:'turkishCoffee',tagline:'',blurb:'',match:()=>false},
);

TURKEY_OBJECTS.push(
  {id:'potteryTr',world:'middle-east',kind:'place',name:'Avanos pottery workshop',zh:'Çömlek atölyesi',emoji:'🏺',area:'anatolia',pos:[18,7],prop:'turkeyPottery',tagline:'River clay turns under the potter’s hands.',blurb:'In Avanos, clay from the Kızılırmak river and nearby hills connects the landscape with the workshop. The potter cleans and kneads it with water, centres it on the wheel and shapes the walls while the clay turns. A steady hand matters more than speed.\n\nThe vessel must dry before it enters a kiln. Firing changes soft clay into hard ceramic: this is what makes a jar useful beyond the day it was made. Cups, bowls and storage vessels carry the workshop’s knowledge into ordinary kitchens.\n\nWatch the wheel turn, then follow the bread to the village courtyard. Food culture includes the tools that hold, cook and serve a meal.',match:()=>false},
  {id:'copperTr',world:'middle-east',kind:'place',name:'The coppersmith’s room',zh:'Bakırcı',emoji:'⚒️',area:'anatolia',pos:[8,7],prop:'turkeyCopper',tagline:'A small hammer gives the street its rhythm.',blurb:'Copperworking remains one of Gaziantep’s living crafts, alongside weaving, shoemaking and wood inlay. A tray or coffee pot begins with a maker who understands the metal, the tool and the shape the object needs to hold. Repeated hammer blows are careful work, even when the workshop sounds busy.\n\nThe finished objects belong in daily life: a tray carries tea glasses, a cezve heats coffee, and serving dishes gather food at the table. Maintenance is part of that life too; traditional copper cookware commonly has a protective lining that needs care.\n\nTap to watch the smith work. Then visit the coffeehouse and look for the same warm copper colour beside the cups.',match:()=>false},
  {id:'fountainTr',world:'middle-east',kind:'landmark',name:'The lane fountain',zh:'Çeşme',emoji:'⛲',area:'istanbul',pos:[-33,-21],prop:'turkeyFountain',tagline:'A little water and a place to pause.',blurb:'A çeşme is a fountain. In Istanbul’s older streets, public water structures were part of the infrastructure of everyday life, not just ornament. Their masonry, spouts and basins made water accessible beyond a private household.\n\nThis small imagined lane fountain links that practical purpose with the world around it: a walker stops, a cat rests nearby, and the route continues towards the market.',match:()=>false},
  {id:'catTr',world:'middle-east',kind:'landmark',name:'A cat in the shade',zh:'Sokak kedisi',emoji:'🐈',area:'istanbul',pos:[-29,-37],prop:'turkishCat',tagline:'The neighbourhood has another regular.',blurb:'Street cats are a familiar presence in Istanbul. People may leave food and water near a doorway or shop, and a cat can become part of the daily rhythm of a particular lane. These relationships depend on ordinary acts of care.\n\nThis one has chosen a quiet spot close to the tea garden. Tap for a purr, then carry on towards the ferry. The city is made of small encounters as well as famous buildings.',match:()=>false},
);
TURKEY_NEXT.potteryTr=['yufkaTr','supperTr'];TURKEY_NEXT.copperTr=['turkishCoffee','teaGarden'];
TURKEY_NEXT.fountainTr=['bazaar','simit'];TURKEY_NEXT.catTr=['teaGarden','balikEkmek'];
TURKEY_OBJECTS.push(
  {id:'hammamTr',world:'middle-east',kind:'place',name:'The neighbourhood hammam',zh:'Hamam',emoji:'🫧',area:'aegean',pos:[-10,5],prop:'turkeyHammam',tagline:'Warm stone, a domed roof and a slower hour.',blurb:'A hammam is a bathhouse. Ottoman bath architecture developed within a longer regional history of public bathing. Domed roofs, small roof lights and rooms of different temperatures turn a practical building into a distinctive part of the town.\n\nBaths also had a social life: people met, prepared for celebrations and made time for care beyond the work of a household. Practices varied by period and place; a neighbourhood bath was not simply a private bathroom made larger.\n\nHere the steam above the dome marks the bath among the kitchens and workshops. Pause at the entrance, then walk back into the lane for tea and something to eat.',match:()=>false},
  {id:'citrusTr',world:'middle-east',kind:'ingredient',name:'The southern citrus orchard',zh:'Narenciye bahçesi',emoji:'🍊',area:'aegean',pos:[38,5],prop:'turkeyCitrus',tagline:'Cultivated coastal land below the foothills.',blurb:'The Mediterranean coast has mild, wetter winters and hot, dry summers. Citrus orchards belong to this cultivated coastal landscape, while the cooler interior and rainy Black Sea slopes support different crops. This small grove gives the southern part of the world a seasonal task as well as a green canopy.\n\nFruit is picked into baskets between the rows. The trees need care through the dry season; a green orchard is a working landscape, not proof that the summer climate is wet. A fresh orange can end a meal, travel home from a market or be shared during a pause in the day.',match:()=>false},
);
TURKEY_NEXT.hammamTr=['teaGarden','mezeTr'];TURKEY_NEXT.citrusTr=['bazaar','kahvalti'];
