import type { WorldObject, Area } from './graph';
import { TURKEY_STORY_DEPTH } from './turkey-stories';

/** Optional story-card links follow ingredients and meals between rooms. */
export const TURKEY_NEXT: Record<string,string[]> = {
  simit:['teaGarden','kahvalti'], teaGarden:['teaHillTr','balikEkmek'],
  turkishCoffee:['sweetShop','teaGarden'], bazaar:['dolmaTr','oliveTr'],
  balikEkmek:['simit','mezeTr'], mangal:['pideTr','supperTr'],
  sweetShop:['turkishCoffee','yufkaTr'], pideTr:['mangal','yufkaTr'],
  yufkaTr:['kahvalti','pideTr'], dolmaTr:['bazaar','oliveTr'],
  kahvalti:['simit','teaGarden'], mezeTr:['oliveTr','balikEkmek'],
  oliveTr:['dolmaTr','mezeTr'], teaHillTr:['teaGarden','kahvalti'],
  supperTr:['yufkaTr','mangal'],
};

type Place = [id:string, name:string, zh:string, area:Area, x:number, z:number, prop:string, scene:string, emoji:string, tagline:string, blurb:string, food:string];
const places: Place[] = [
  ['simit','Simit by the ferry','Simitçi','istanbul',-31,-38,'turkeySimitCart','tr_simit','🥨','A sesame ring for the crossing.','Warm simit, cheese and tea are part of an ordinary Istanbul morning. Walk along the quay, stop at the cart, and watch the ferries connect the two shores.','simit'],
  ['teaGarden','Waterfront tea garden','Çay bahçesi','istanbul',-20,-38,'turkeyTeaGarden','tr_tea','🫖','Tea, backgammon and the Bosphorus.','A tea garden is a place to sit with friends and family. Tulip glasses are refilled, backgammon pieces move across the board, and conversation can last all afternoon.','tea'],
  ['turkishCoffee','Neighbourhood coffeehouse','Kahvehane','istanbul',-3.8,-35,'turkeyCoffee','tr_coffee','☕','A small cup and time to talk.','Finely ground coffee is heated in a cezve and served unfiltered in a small cup. The preparation belongs with the welcome: water, coffee and a visit that need not be hurried.','coffee'],
  ['bazaar','The covered bazaar','Kapalıçarşı esintisi','istanbul',-20,-26,'turkeyBazaar','tr_market','🍅','Arches, spice bowls and a basket for supper.','A Grand Bazaar-inspired arcade opens onto a neighbourhood produce market. Carpets, copperware and ceramics frame the stalls; peppers, aubergines, tomatoes, olives and herbs connect this trading street with the kitchens nearby.','dolma'],
  ['balikEkmek','Fish at the quay','Balık ekmek','istanbul',-45,-38,'turkeyFish','tr_fish','🐟','Grilled fish and bread beside the water.','Istanbul’s waterfront is a place to eat as well as travel. Fish sandwiches, onions and greens meet ferry queues, fishermen and the changing light on the Bosphorus.','balik-ekmek'],
  ['mangal','Charcoal kitchen','Ocakbaşı','istanbul',-22,-13,'turkeyKebab','tr_kebab','🍢','Skewers turn above glowing coals.','At an ocakbaşı the charcoal hearth is part of the meal. Şiş, grilled peppers, bread, onion with sumac and a cool ayran are familiar companions. Regional kebab styles vary across Türkiye.','sis'],
  ['sweetShop','Baklava workshop','Baklavacı','anatolia',7,-26,'turkeyBaklava','tr_baklava','🍯','Thin pastry, butter and pistachios.','Gaziantep is closely associated with pistachio baklava. In the workshop, pastry is rolled thin, layered with butter and nuts, cut into portions and baked before syrup is added.','baklava'],
  ['pideTr','Pide and lahmacun oven','Pide fırını','anatolia',19,-12,'turkeyPide','tr_pide','🫓','The hot oven feeds the lane.','A boat-shaped pide holds its filling inside a raised rim. Lahmacun is a thin round with a minced meat, vegetable and herb topping, often eaten with parsley and lemon.','pide'],
  ['yufkaTr','Village bread courtyard','Yufka ve gözleme','anatolia',7,-12,'turkeyYufka','tr_yufka','🥖','Rolling pins, thin dough and shared work.','Yufka is rolled thin; it can become layered börek or folded gözleme with cheese, greens or another savoury filling. Making bread together turns preparation into a social activity.','borek'],
  ['dolmaTr','The dolma kitchen','Dolma ve sarma','aegean',-34,0,'turkeyDolma','tr_dolma','🫑','Fill a pepper, roll a leaf.','Dolma means filled; sarma means wrapped. Rice, herbs, vegetables and sometimes meat come together in recipes that vary by home and region. Olive-oil preparations are often served cool.','sarma'],
  ['kahvalti','The breakfast house','Kahvaltı','istanbul',-4,-24,'turkeyBreakfast','tr_breakfast','🍳','A long table of small morning plates.','Cheese, olives, tomatoes, cucumber, eggs, bread, honey and tea bring sweet and savoury tastes to breakfast. Families and friends linger over a spread that changes from region to region.','breakfast'],
  ['mezeTr','Aegean meze table','Meze sofrası','aegean',-38,-13,'turkeyMeze','tr_meze','🥗','Vegetables, yogurt and herbs to share.','Small plates invite everyone to try a little. Aubergine, yogurt, olive oil and fresh herbs sit alongside bread and warm dishes; the meal grows with the conversation.','meze'],
  ['oliveTr','Aegean olive grove','Zeytinlik','aegean',-47,0,'turkeyOliveGrove','tr_olive','🫒','Silver leaves above the harvest baskets.','The Aegean coast connects olive groves with everyday kitchens. Oil seasons vegetables, bread and fish. Table olives are cured before they become part of breakfast.','olive-oil'],
  ['teaHillTr','Black Sea tea terraces','Karadeniz çaylıkları','blacksea-tr',38,-34,'turkeyTeaHill','tr_tea_hill','🌿','Rainy hills supply the tea glass.','Around Rize, tea rows climb the green eastern Black Sea hills. Harvested leaves are processed into the black tea poured in homes, shops and tea gardens across Türkiye.','tea-leaves'],
  ['supperTr','Anatolian family supper','Akşam sofrası','anatolia',31,-12,'turkeySupper','tr_supper','🫕','Soup, bread, bulgur and a pot to share.','Everyday cooking belongs beside the famous street foods: lentil soup, bulgur pilaf, vegetable dishes and slow-cooked pots. Mantı brings small filled dumplings together with yogurt and spiced butter.','stew'],
];

export const TURKEY_CARD_ART: Record<string,string> = Object.fromEntries(places.map(p=>[p[0],p[11]]));
TURKEY_CARD_ART['stall-nuts']='pistachios';
export const TURKEY_OBJECTS: WorldObject[] = places.map(([id,name,zh,area,x,z,prop,scene,emoji,tagline,blurb])=>({
  id,world:'middle-east',kind:'place',name,placeName:name,zh,area,pos:[x,z],prop,scene,emoji,tagline,blurb:blurb+"\n\n"+TURKEY_STORY_DEPTH[id],place:true,rot:0,
  elevation:id==='teaHillTr'?4.5:id==='yufkaTr'?1:id==='supperTr'?1.2:0,
  match:r=>r.place===id,
}));
// The stalls remain available inside the painted market, with Turkish names and relevant local links.
TURKEY_OBJECTS.push(
  {id:'spicesMe',world:'middle-east',kind:'flavour',name:'Sumac and pepper flakes',zh:'Sumak ve pul biber',emoji:'🌶️',area:'istanbul',pos:[-25.5,-28.6],prop:'none',hitOnly:true,parent:'bazaar',tagline:'Sour red berries, warm red pepper.',blurb:'Sumac brings a tart taste to onion salads; pul biber adds warmth to many dishes. Explore the charcoal counter to see how seasonings accompany the grill.',partners:['sumac','paprika','yogurt'],match:r=>r.core.some(i=>/sumac|paprika|cumin/.test(i))},
  {id:'sweets',world:'middle-east',kind:'dish',name:'Baklava and pistachios',zh:'Baklava ve fıstık',emoji:'🍯',area:'istanbul',pos:[-15.5,-28.6],prop:'none',hitOnly:true,parent:'bazaar',alias:'sweetShop',tagline:'',blurb:'',match:()=>false},
  {id:'tea',world:'middle-east',kind:'dish',name:'Tea and hospitality',zh:'Çay',emoji:'🫖',area:'istanbul',pos:[-19,-23.4],prop:'none',hitOnly:true,parent:'bazaar',alias:'teaGarden',tagline:'',blurb:'',match:()=>false},
  {id:'stall-olives',world:'middle-east',kind:'ingredient',name:'Olives and oil',zh:'Zeytin',emoji:'🫒',area:'istanbul',pos:[-14,-23.4],prop:'none',hitOnly:true,parent:'bazaar',alias:'oliveTr',tagline:'',blurb:'',match:()=>false},
  {id:'stall-nuts',world:'middle-east',kind:'ingredient',name:'Nuts and dried fruit',zh:'Kuruyemiş',emoji:'🥜',area:'istanbul',pos:[-24,-23.4],prop:'none',hitOnly:true,parent:'bazaar',tagline:'Pistachios, walnuts, dried apricots and raisins by the scoop.',blurb:'Kuruyemiş shops bring nuts, seeds and dried fruit together. A small bag may be a snack in its own right, something to offer a visitor, or an ingredient carried home for cooking. The seller can measure out a handful for the walk home.\n\nDrying fruit removes much of its water and allows part of a seasonal harvest to be stored. Nuts and dried fruit bring different textures to the same counter: crisp kernels, chewy apricots, figs and raisins. The selection varies by region and season.\n\nLook at the bowls before choosing a route. Follow pistachios to the pastry workshop to see one use, or return to the market to choose what goes home for supper.',match:()=>false},
  {id:'stall-lamps',world:'middle-east',kind:'landmark',name:'Tea sets and lamps',zh:'Çay takımları',emoji:'🪔',area:'istanbul',pos:[-20.5,-28.6],prop:'none',hitOnly:true,parent:'bazaar',alias:'turkishCoffee',tagline:'',blurb:'',match:()=>false},
);

TURKEY_OBJECTS.push(
  {id:'potteryTr',world:'middle-east',kind:'place',name:'Avanos pottery workshop',zh:'Çömlek atölyesi',emoji:'🏺',area:'anatolia',pos:[18,7],prop:'turkeyPottery',tagline:'River clay turns under the potter’s hands.',blurb:'In Avanos, clay from the Kızılırmak river and nearby hills connects the landscape with the workshop. The potter cleans and kneads it with water, centres it on the wheel and shapes the walls while the clay turns. A steady hand matters more than speed.\n\nThe vessel must dry before it enters a kiln. Firing changes soft clay into hard ceramic: this is what makes a jar useful beyond the day it was made. Cups, bowls and storage vessels carry the workshop’s knowledge into ordinary kitchens.\n\nWatch the wheel turn, then follow the bread to the village courtyard. Food culture includes the tools that hold, cook and serve a meal.',match:()=>false},
  {id:'copperTr',world:'middle-east',kind:'place',name:'The coppersmith’s room',zh:'Bakırcı',emoji:'⚒️',area:'anatolia',pos:[8,7],prop:'turkeyCopper',tagline:'A small hammer gives the street its rhythm.',blurb:'Copperworking remains one of Gaziantep’s living crafts, alongside weaving, shoemaking and wood inlay. A tray or coffee pot begins with a maker who understands the metal, the tool and the shape the object needs to hold. Repeated hammer blows are careful work, even when the workshop sounds busy.\n\nThe finished objects belong in daily life: a tray carries tea glasses, a cezve heats coffee, and serving dishes gather food at the table. Maintenance is part of that life too; traditional copper cookware commonly has a protective lining that needs care.\n\nTap to watch the smith work. Then visit the coffeehouse and look for the same warm copper colour beside the cups.',match:()=>false},
  {id:'fountainTr',world:'middle-east',kind:'landmark',name:'The İznik-tiled fountain',zh:'Çinili çeşme',emoji:'⛲',area:'istanbul',pos:[-31,-12],prop:'turkeyFountain',tagline:'Blue tiles, flowing water and a place to pause.',blurb:'A çeşme is a fountain. In Istanbul’s older streets, public water structures were part of the infrastructure of everyday life. Their masonry, spouts and basins made water accessible beyond a private household.\n\nOne famous Istanbul example, the Fountain of Ahmed III, dates to 1728–1729. Such structures could combine a practical water supply with a patron’s public gift and an elaborate architectural presence. The tiled fountain here evokes that civic role rather than reproducing that particular monument.\n\nThis imagined square fountain uses blue-and-white tile patterns inspired by Ottoman ceramic decoration. Water flows into the four basins beneath a broad roof. The cool colours make a meeting point among warm stone, wooden bays and terracotta roofs.\n\nA walker stops, a cat rests nearby, and the route continues towards the market. Follow the simit cart down to the quay or the smell of charcoal towards the next counter.',match:()=>false},
  {id:'catTr',world:'middle-east',kind:'landmark',name:'A cat in the shade',zh:'Sokak kedisi',emoji:'🐈',area:'istanbul',pos:[-29,-37],prop:'turkishCat',tagline:'The neighbourhood has another regular.',blurb:'Street cats are a familiar presence in Istanbul. People may leave food and water near a doorway or shop, and a cat can become part of the daily rhythm of a particular lane. These relationships depend on ordinary acts of care.\n\nThis one has chosen a quiet spot close to the tea garden. Tap for a purr, then carry on towards the ferry. The city is made of small encounters as well as famous buildings.',match:()=>false},
);
TURKEY_NEXT.potteryTr=['yufkaTr','supperTr'];TURKEY_NEXT.copperTr=['turkishCoffee','teaGarden'];
TURKEY_NEXT.fountainTr=['bazaar','simit'];TURKEY_NEXT.catTr=['teaGarden','balikEkmek'];
TURKEY_OBJECTS.push(
  {id:'hammamTr',world:'middle-east',kind:'place',name:'The neighbourhood hammam',zh:'Hamam',emoji:'🫧',area:'aegean',pos:[-10,5],prop:'turkeyHammam',tagline:'Warm stone, a domed roof and a slower hour.',blurb:'A hammam is a bathhouse. Ottoman bath architecture developed within a longer regional history of public bathing. Domed roofs, small roof lights and rooms of different temperatures turn a practical building into a distinctive part of the town.\n\nA surviving example is Çemberlitaş Hamamı, founded in 1584 for Nurbanu Sultan. Income from the bath helped support the Atik Valide charitable complex. This connects bathing with the Ottoman endowment system: a working neighbourhood building could help fund services elsewhere in the city.\n\nBaths also had a social life: people met, prepared for celebrations and made time for care beyond the work of a household. Practices varied by period and place; a neighbourhood bath was not simply a private bathroom made larger.\n\nHere the steam above the dome marks the bath among the kitchens and workshops. Pause at the entrance, then walk back into the lane for tea and something to eat.',match:()=>false},
  {id:'citrusTr',world:'middle-east',kind:'ingredient',name:'The southern citrus orchard',zh:'Narenciye bahçesi',emoji:'🍊',area:'aegean',pos:[38,5],prop:'turkeyCitrus',tagline:'Cultivated coastal land below the foothills.',blurb:'The Mediterranean coast has mild, wetter winters and hot, dry summers. Citrus orchards belong to this cultivated coastal landscape, while the cooler interior and rainy Black Sea slopes support different crops. This small grove gives the southern part of the world a seasonal task as well as a green canopy.\n\nFruit is picked into baskets between the rows. The trees need care through the dry season; a green orchard is a working landscape, not proof that the summer climate is wet. A fresh orange can end a meal, travel home from a market or be shared during a pause in the day.',match:()=>false},
);
TURKEY_NEXT.hammamTr=['teaGarden','mezeTr'];TURKEY_NEXT.citrusTr=['bazaar','kahvalti'];

TURKEY_OBJECTS.push(
  {id:'mosqueTr',world:'middle-east',kind:'landmark',name:'The Ottoman mosque skyline',zh:'Sultanahmet esintisi',emoji:'🕌',area:'istanbul',pos:[-38,-28],prop:'turkeyMosque',tagline:'Lead domes and six slender minarets above the town.',blurb:'The layered domes and six minarets evoke Istanbul’s Sultan Ahmed Mosque, often called the Blue Mosque. This is an imagined architectural landmark, compressed to the scale of the food world. It is a place of worship as well as a familiar part of the city’s skyline.\n\nThe Sultan Ahmed Mosque was built between 1609 and 1617 for Sultan Ahmed I, with Sedefkâr Mehmed Ağa as architect. Its early seventeenth-century silhouette belongs to a specific moment in Ottoman Istanbul, even though this miniature gathers it beside foods and transport from other periods.\n\nLook at how the smaller domes lead towards the large central dome, and how the courtyard brings the monumental building back to the scale of people. Ottoman urban life connected religious buildings with fountains, streets, shops and places to meet.\n\nFrom the quiet courtyard, the town opens towards the bazaar and the waterfront. Food belongs to that surrounding everyday life: a simit on the way to the ferry, tea after a visit and ingredients carried home from the market.',match:()=>false},
  {id:'ottomanTr',world:'middle-east',kind:'landmark',name:'The Ottoman timber house',zh:'Cumbalı ev',emoji:'🏠',area:'istanbul',pos:[-4.1,-29],prop:'turkeyOttoman',tagline:'A projecting bay watches the neighbourhood go by.',blurb:'Historic Ottoman houses often combine a substantial lower storey with lighter upper rooms. In towns such as Safranbolu, timber construction, pale plaster and projecting bays give narrow streets a distinctive shape. Building traditions vary across Türkiye; these houses are one part of that variety.\n\nSafranbolu prospered as an important caravan-trade centre, especially during the seventeenth century. Its surviving historic town shows how wealth, craft and domestic needs shaped houses and streets over time. The bays here draw on that architectural tradition rather than representing every Turkish house or one exact construction date.\n\nThe projecting bay, or cumba, brings more light and a view along the street. Wooden brackets carry the overhang; tiled eaves shelter the walls below. Shutters, flower boxes and household objects make the architecture feel inhabited.\n\nHere the house sits between the coffeehouse and the breakfast table. Follow those neighbours to see how the street connects a private home with shared food and conversation.',match:()=>false},
  {id:'waterfrontTr',world:'middle-east',kind:'landmark',name:'The Bosphorus waterfront',zh:'Boğaz kıyısı',emoji:'⛴️',area:'istanbul',pos:[-37,-44.8],prop:'none',hitOnly:true,hit:[8,1.8,1.1,.9],tagline:'Ferries, gulls and something warm for the crossing.',blurb:'The Bosphorus is the strait that runs through Istanbul between its European and Asian shores. Ferries make the water part of daily travel. This miniature waterfront evokes that relationship through a promenade, passing boats and food stalls close to the landing.\n\nIn 1851, Şirket-i Hayriye was established to operate steam ferries on the Bosphorus. Regular crossings helped connect shore settlements and the growing city. Today’s ferry culture sits within that longer history of making a waterway part of an ordinary daily route.\n\nThe blue water gives the town breathing space. Watch a ferry cross the view, then follow the people back towards tea glasses, sesame rings and fish in bread. Eating beside the water can be a short pause in a busy day.\n\nThe map compresses several Turkish landscapes into one explorable world. Its continuous sea also leads towards the rainy tea slopes; those regions are represented together here rather than at their real distances.',match:()=>false},
  {id:'cappadociaTr',world:'middle-east',kind:'landmark',name:'Cappadocia’s rock valley',zh:'Kapadokya',emoji:'🎈',area:'anatolia',pos:[17,-35],prop:'none',hitOnly:true,hit:[10,7,9,3.5],tagline:'Fairy chimneys beneath slowly drifting balloons.',blurb:'Cappadocia’s distinctive landscape formed in volcanic deposits that were shaped by erosion. Harder caps can protect softer rock below, helping create the tall formations often called fairy chimneys. People also adapted the soft rock into spaces for living, storing and worship.\n\nChristian monastic communities were present in the region from the fourth century. Göreme’s rock-cut churches preserve an important Byzantine legacy, including rich decoration from after the end of Iconoclasm in 842. The religious spaces and the much older eroded volcanic landscape tell different layers of the valley’s history.\n\nThe balloons provide a gently changing view of the valley. They are a contemporary visitor experience above a landscape with a much longer history. Here the rocks sit behind the town so the food streets remain the centre of exploration.\n\nContinue towards Avanos and the pottery workshop, then to a village bread table. The region’s cultural landscape includes skilled hands and everyday meals as well as a memorable silhouette.',match:()=>false},
  {id:'donerTr',world:'middle-east',kind:'dish',name:'The döner stand',zh:'Dönerci',emoji:'🥙',area:'istanbul',pos:[-17.2,5.4],prop:'turkeyDoner',tagline:'The spit turns; the next portion is sliced thin.',blurb:'Döner takes its name from turning. A vertical stack rotates beside the heat so that its outside cooks while the inner layers stay away from the hottest surface. Thin slices are shaved from the browned exterior as portions are served.\n\nBread, greens, onions and accompaniments vary with the shop and the style of service. A döner sandwich belongs to a different preparation from pieces of meat threaded onto şiş skewers, even though both may be found along the same busy food street.\n\nTap to watch the stand respond, then visit the charcoal kitchen to compare the two ways of cooking. The turning motion is part of the practical work behind a quick meal.',match:()=>false},
  {id:'gozlemeTr',world:'middle-east',kind:'dish',name:'Gözleme on the griddle',zh:'Sacda gözleme',emoji:'🫓',area:'anatolia',pos:[7,-1.5],prop:'turkeyGozleme',tagline:'Thin dough, a savoury filling and a hot sac.',blurb:'Gözleme begins with thin dough, spread with a savoury filling and folded before cooking on a broad griddle called a sac. Cheese, greens, potato and meat are among the many fillings; recipes and shapes vary.\n\nRolling the dough evenly helps it cook before the outside becomes too dark. A cook watches the surface, turns the bread and presses it against the heat where needed. The crisp browned patches and softer folded layers are part of its appeal.\n\nThis small outdoor station sits near the bread courtyard and the pide oven. Follow the same flour through three preparations: rolled flatbread, folded gözleme and an oven-baked pide with its raised edge.',match:()=>false},
);
TURKEY_NEXT.mosqueTr=['bazaar','simit'];TURKEY_NEXT.ottomanTr=['kahvalti','turkishCoffee'];
TURKEY_NEXT.waterfrontTr=['balikEkmek','teaGarden'];TURKEY_NEXT.cappadociaTr=['yufkaTr','supperTr'];
TURKEY_NEXT.donerTr=['mangal','bazaar'];TURKEY_NEXT.gozlemeTr=['yufkaTr','pideTr'];

TURKEY_NEXT['stall-nuts']=['bazaar','sweetShop'];
